/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemaPlaygroundRouteImport } from './routes/schema-playground'
import { Route as FormViewerRouteImport } from './routes/form-viewer'
import { Route as FormPlaygroundRouteImport } from './routes/form-playground'
import { Route as IndexRouteImport } from './routes/index'

const SchemaPlaygroundRoute = SchemaPlaygroundRouteImport.update({
  id: '/schema-playground',
  path: '/schema-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const FormViewerRoute = FormViewerRouteImport.update({
  id: '/form-viewer',
  path: '/form-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const FormPlaygroundRoute = FormPlaygroundRouteImport.update({
  id: '/form-playground',
  path: '/form-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/form-viewer': typeof FormViewerRoute
  '/schema-playground': typeof SchemaPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/form-viewer': typeof FormViewerRoute
  '/schema-playground': typeof SchemaPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-playground': typeof FormPlaygroundRoute
  '/form-viewer': typeof FormViewerRoute
  '/schema-playground': typeof SchemaPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form-playground' | '/form-viewer' | '/schema-playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form-playground' | '/form-viewer' | '/schema-playground'
  id:
    | '__root__'
    | '/'
    | '/form-playground'
    | '/form-viewer'
    | '/schema-playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormPlaygroundRoute: typeof FormPlaygroundRoute
  FormViewerRoute: typeof FormViewerRoute
  SchemaPlaygroundRoute: typeof SchemaPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema-playground': {
      id: '/schema-playground'
      path: '/schema-playground'
      fullPath: '/schema-playground'
      preLoaderRoute: typeof SchemaPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-viewer': {
      id: '/form-viewer'
      path: '/form-viewer'
      fullPath: '/form-viewer'
      preLoaderRoute: typeof FormViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-playground': {
      id: '/form-playground'
      path: '/form-playground'
      fullPath: '/form-playground'
      preLoaderRoute: typeof FormPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormPlaygroundRoute: FormPlaygroundRoute,
  FormViewerRoute: FormViewerRoute,
  SchemaPlaygroundRoute: SchemaPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
